### ISSUE TITLE
compile_pretty causing an OS error of filename being too long

### ISSUE THREAD

**Issue by gadzair** [AeonLucid/POGOProtos#175]
POGOProtos foo$ python compile_pretty.py csharp
Traceback (most recent call last):
  File "compile_pretty.py", line 449, in <module>
    call(command, shell=False)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 63] File name too long

**Comment by AeonLucid** [comment]
@ehoepfner

**Comment by ghost** [comment]
@gadzair It is fixed now. If it is still giving you an error, then your protoc is probably too old and cannot compile version 3 .proto files.

**Comment by gadzair** [comment]
@ehoepfner 

Nope it still doesn't work. I am able to compile .proto files and the following works just fine:
python compile_single.py -l csharp

python compile_pretty.py csharp still fails with the same error using your PR here: https://github.com/AeonLucid/POGOProtos/pull/176

**Comment by gadzair** [comment]
I did a print of the command that is causing the issue and here is the full output:

fobar$ python compile_pretty.py csharp
"protoc" --proto_path="/Users/fobar/play/POGOProtos/out" --descriptor_set_out="/Users/fobar/play/POGOProtos/out/POGOProtos.desc"  "/Users/fobar/play/POGOProtos/out/POGOProtos/Inventory/Item/ItemId.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Inventory/Item/ItemData.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Inventory/Item/ItemType.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Inventory/Item/ItemAward.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/FortSearchResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/UseIncenseResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/NicknamePokemonResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/CheckAwardedBadgesResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/EncounterTutorialCompleteResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/SetPlayerTeamResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/GetMapObjectsResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/GetPlayerResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/FortDeployPokemonResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/SetFavoritePokemonResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/GetInventoryResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/UseItemReviveResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/GetIncensePokemonResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/EchoResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/CheckCodenameAvailableResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/EquipBadgeResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/DownloadSettingsResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/SetAvatarResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/IncenseEncounterResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/ClaimCodenameResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/UpgradePokemonResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/AttackGymResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/GetGymDetailsResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/DownloadRemoteConfigVersionResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/EncounterResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/SfidaActionLogResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/GetPlayerProfileResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/GetSuggestedCodenamesResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/FortRecallPokemonResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/FortDetailsResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/GetDownloadUrlsResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/MarkTutorialCompleteResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/UseItemEggIncubatorResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/DiskEncounterResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/CollectDailyDefenderBonusResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/SetContactSettingsResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/CatchPokemonResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/UseItemPotionResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/UseItemXpBoostResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/AddFortModifierResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/DownloadItemTemplatesResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/LevelUpRewardsResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/PlayerUpdateResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/CollectDailyBonusResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/GetHatchedEggsResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/RecycleInventoryItemResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/UseItemGymResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/UseItemCaptureResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/StartGymBattleResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/GetAssetDigestResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/EvolvePokemonResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Responses/ReleasePokemonResponse.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/GetIncensePokemonMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/PlayerUpdateMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/UseItemGymMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/MarkTutorialCompleteMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/StartGymBattleMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/EncounterTutorialCompleteMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/AttackGymMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/ClaimCodenameMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/GetDownloadUrlsMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/SetAvatarMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/DownloadRemoteConfigVersionMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/EquipBadgeMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/CheckAwardedBadgesMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/GetSuggestedCodenamesMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/AddFortModifierMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/CollectDailyDefenderBonusMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/CollectDailyBonusMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/RecycleInventoryItemMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/DiskEncounterMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/UseItemReviveMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/LevelUpRewardsMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/FortDetailsMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/FortDeployPokemonMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/UseItemCaptureMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/UseIncenseMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/GetInventoryMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/SetContactSettingsMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/SfidaActionLogMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/EvolvePokemonMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/EncounterMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/SetFavoritePokemonMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/CheckCodenameAvailableMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/NicknamePokemonMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/EchoMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/GetPlayerProfileMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/FortSearchMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/GetGymDetailsMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/UseItemXpBoostMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/GetMapObjectsMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/GetAssetDigestMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/GetHatchedEggsMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/UpgradePokemonMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/ReleasePokemonMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/CatchPokemonMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/IncenseEncounterMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/UseItemEggIncubatorMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/SetPlayerTeamMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/DownloadItemTemplatesMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/DownloadSettingsMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/FortRecallPokemonMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/UseItemPotionMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Messages/GetPlayerMessage.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Battle/BattleActionType.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Battle/BattleAction.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Battle/BattleLog.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Battle/BattlePokemonInfo.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Battle/BattleType.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Battle/BattleParticipant.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Battle/BattleResults.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Battle/BattleState.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Logs/ActionLogEntry.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Logs/CatchPokemonLogEntry.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Logs/FortSearchLogEntry.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/IapItemCategory.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/ActivityType.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/ItemEffect.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/PokemonId.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/BadgeType.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/PokemonRarity.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/Gender.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/PokemonFamilyId.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/ItemCategory.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/TutorialState.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/PokemonMovementType.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/Platform.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/PokemonType.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/CameraTarget.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/PokemonMove.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/TeamColor.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Enums/CameraInterpolation.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Map/Fort/FortModifier.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Map/Fort/FortData.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Map/Fort/FortRenderingType.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Map/Fort/FortLureInfo.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Map/Fort/FortType.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Map/Fort/FortSponsor.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Map/Fort/FortSummary.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Map/Pokemon/MapPokemon.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Map/Pokemon/WildPokemon.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Map/Pokemon/NearbyPokemon.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Capture/CaptureAward.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Capture/CaptureProbability.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Envelopes/Unknown6Response.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Envelopes/ResponseEnvelope.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Envelopes/AuthTicket.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Envelopes/Signature.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Envelopes/Unknown6.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Envelopes/RequestEnvelope.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Map/MapObjectsStatus.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Map/MapCell.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Map/SpawnPoint.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Gym/GymMembership.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Gym/GymState.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Inventory/EggIncubatorType.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Inventory/InventoryUpgradeType.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Inventory/InventoryDelta.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Inventory/AppliedItem.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Inventory/Candy.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Inventory/InventoryItemData.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Inventory/EggIncubator.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Inventory/EggIncubators.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Inventory/AppliedItems.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Inventory/InventoryUpgrade.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Inventory/InventoryItem.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Inventory/InventoryUpgrades.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/InventorySettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/GlobalSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/FortSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/MapSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/DownloadSettingsAction.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/LevelSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/PokemonData.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/PlayerBadge.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/AssetDigestEntry.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/DownloadUrlEntry.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/PlayerData.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/PokedexEntry.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/GymLevelSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/PlayerLevelSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/CameraSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/EncounterSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/ItemSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/MoveSequenceSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/IapItemDisplay.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/GymBattleSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/PokemonUpgradeSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/EquippedBadgeSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/PokemonSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/MoveSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/TypeEffectiveSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/IapSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/BadgeSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/RequestType.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Networking/Requests/Request.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/Item/FortModifierAttributes.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/Item/BattleAttributes.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/Item/ExperienceBoostAttributes.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/Item/ReviveAttributes.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/Item/EggIncubatorAttributes.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/Item/InventoryUpgradeAttributes.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/Item/IncenseAttributes.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/Item/PotionAttributes.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/Item/FoodAttributes.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/Item/PokeballAttributes.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/Pokemon/StatsAttributes.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/Pokemon/CameraAttributes.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Settings/Master/Pokemon/EncounterAttributes.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Player/PlayerAvatar.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Player/ContactSettings.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Player/PlayerCamera.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Player/EquippedBadge.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Player/PlayerStats.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Player/Currency.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Player/PlayerPublicProfile.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Player/DailyBonus.proto" "/Users/fobar/play/POGOProtos/out/POGOProtos/Data/Player/PlayerCurrency.proto"
Traceback (most recent call last):
  File "compile_pretty.py", line 451, in <module>
    call(command, shell=False)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 63] File name too long

**Comment by nabeelamjad** [comment]
If you change https://github.com/ehoepfner/POGOProtos/blob/d4ba07a658f6b45a37c0e335256d26b39e321c3a/compile_pretty.py#L450 to `call(command, shell=True)` it appears to work fine.

**Comment by ghost** [comment]
I suspect that the compile command is somehow to long with all the files as arguments.

@nabeelamjad Yes, you are right. But with shell=True it fails on Windows with "The command line is too long.". That's why I changed it to False originally.

So I put in a check if  the OS is Windows or not and then set the shell argument appropriately.

**Comment by luisa123456** [comment]
Long Path Tool is the perfect utility that can solve all the long path issues. Download this software online.

**Comment by Stepan222** [comment]
Long too path error?
“Long path tool” is very helpful for this problem. 
You can solve this problem like copy, delete, long path files by using this tool. I used to have similar problems too, but after using “long path tool” everything was solved."
